name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  test-staging-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_PRIVATE_KEY}}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{secrets.STAGING_HOST}}" >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key ${{secrets.STAGING_USER}}@${{secrets.STAGING_HOST}} "cd ${{secrets.STAGING_APP_DIR}} && pwd && hostname"

      - name: Check remote runtime
        run: |
          ssh -i ~/.ssh/deploy_key ${{secrets.STAGING_USER}}@${{secrets.STAGING_HOST}} '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd ${{ secrets.STAGING_APP_DIR }}

            node -v
            pnpm -v
            pm2 -v
          '

      - name: Sync latest code on staging
        run: |
          ssh -i ~/.ssh/deploy_key ${{secrets.STAGING_USER}}@${{secrets.STAGING_HOST}} '
            cd ${{secrets.STAGING_APP_DIR}}

            git fetch origin main
            git reset --hard origin/main
            
            git rev-parse --short HEAD
          '

      - name: Install dependencies on staging
        run: |
          ssh -i ~/.ssh/deploy_key ${{secrets.STAGING_USER}}@${{secrets.STAGING_HOST}} '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd ${{ secrets.STAGING_APP_DIR }}

            pnpm install --frozen-lockfile
          '

      - name: Run Prisma on staging
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd ${{ secrets.STAGING_APP_DIR }}

            pnpm --filter @repo/db db:generate
            pnpm --filter @repo/db db:deploy
          '

      - name: Build app on staging
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            cd ${{ secrets.STAGING_APP_DIR }}

            pnpm run build
          '
      
      - name: Restarting staging services
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            pm2 restart http-server --update-env
            pm2 restart ws-server --update-env
            pm2 restart fe-server --update-env

            pm2 ls
          '
      - name: Health check staging
        run: |
          curl -f http://staging.ci-cd-aws-monorepo-http.kushagrasuryawanshi.com
          curl -f -I http://staging.ci-cd-aws-monorepo-fe.kushagrasuryawanshi.com